name: Generate Changelog

on:
  push:
    branches:
      - main
      - center-horizontally
    tags:
      - "v*.*.*"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Generate Changelog
        run: |
          github_changelog_generator --user joshuadanpeterson --project typewriter.nvim --token ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changelog
        run: |
          git config --local user.name 'GitHub Action'
          git config --local user.email 'action@github.com'
          git add CHANGELOG.md
          git commit -m 'Update changelog' || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
