name: Generate Changelog

on:
  push:
    tags:
      - "v*.*.*" # This will trigger on version tags like v0.0.1, v0.1.0, v1.0.0, etc.
  workflow_dispatch: # This allows manual triggering of the workflow from the GitHub Actions tab.

permissions:
  contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to use Node.js 20

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" # Specify the version of Ruby

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Update remote URL
        run: git remote set-url origin https://github.com/joshuadanpeterson/typewriter.nvim.git

      - name: Generate Changelog
        run: |
          github_changelog_generator --user joshuadanpeterson --project typewriter.nvim --token ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changelog
        run: |
          git config --global user.name 'Josh Peterson'
          git config --global user.email 'joshuadanpeterson@gmail.com'
          git add CHANGELOG.md
          git commit -m 'Update changelog'
          git push origin HEAD:${{ github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
