name: Type Check Code Base
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0
